apiVersion: v1
kind: PersistentVolume
metadata:
  name: chatsapp-pv
  namespace: chat-app
spec:
  capacity:
    storage: 5Gi
  
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data
  
